name: workflow test
on:
  workflow_dispatch:
jobs:
  a_simple_job:
    name: simple jobs
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        id: stepId
        run: echo "first step"
      - name: step with another shell
        id: schellStep
        shell: python
        run: print("printing something")
